environment:

  matrix:

    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

platform:
    -x64

install:
  - "%PYTHON%\\python.exe -m pip install tox pip setuptools --upgrade"

build: false

test_script:
  - "build.cmd %PYTHON%\\python.exe -m tox -e test"
  - "build.cmd %PYTHON%\\python.exe -m tox -e docs"
