resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: aperiosoftware
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    xvfb: true
    coverage: codecov

    envs:

    - linux: py36-imagetest
    - linux: py37-imagetest
    - linux: py38-imagetest
    - linux: py38-notebook
    - linux: py38-docs

    - macos: py36-image
    - macos: py37-image
    - macos: py38-image
    - macos: py38-notebook
    - macos: py38-docs

    - windows: py36-image
    - windows: py37-image
    - windows: py38-image
    - windows: py38-notebook
    - windows: py38-docs

- template: publish.yml@OpenAstronomy
  parameters:
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
      pypi_connection_name: 'pypi_endpoint'
    targets:
    - sdist
    - wheels_universal
    dependsOn:
    - Linux
    - MacOSX
    - Windows
