jobs:

- template: azure-template.yml
  parameters:
    name: Linux
    os: linux
    tox_pre: HOME=/home/testuser DISPLAY=:99.0 sudo -u testuser
    tox_test_env: test-image

- template: azure-template.yml
  parameters:
    name: MacOSX
    os: macosx

- template: azure-template.yml
  parameters:
    name: Windows
    os: windows
